#%RAML 1.0
title: RetrieveTravelOnTipRoutesAndSchedules SAPI
description: This api wil fetch routes and schedules from travelontip system

uses:
  common: /libraries/common/commonBusiness-library.raml

types:
    commonError: !include /libraries/common/dataTypes/common-error-dataType.raml
    getRoutesResponse: !include /libraries/routes/dataTypes/getRoutes-200Response-dataType.raml
    getSchedulesResponse: !include /libraries/schedules/dataTypes/getSchedules-200Response-dataType.raml

/{transportType}:
  /{transportCompany}:
    /routes:
      get:
        is:
          - common.transactionId
        responses:
          200:
            body:
              application/json:
                type: getRoutesResponse
                example: !include /libraries/routes/examples/getRoutes-200Response-example.json
          400:
            body:
              application/json:
                type: commonError
                example: !include /libraries/common/examples/400Response-example.json
          404:
            body:
              application/json:
                type: commonError
                example: !include /libraries/common/examples/404Response-example.json
          500:
            body:
              application/json:
                type: commonError
                example: !include /libraries/common/examples/500Response-example.json
    /schedules:
      get:
        is:
          - common.transactionId
          - common.departureLocationCode
          - common.destinationLocationCode
        responses:
          200:
            body:
              application/json:
                type: getSchedulesResponse
                example: !include /libraries/schedules/examples/getSchedules-200Response-example.json
          400:
            body:
              application/json:
                type: commonError
                example: !include /libraries/common/examples/400Response-example.json
          404:
            body:
              application/json:
                type: commonError
                example: !include /libraries/common/examples/404Response-example.json
          500:
            body:
              application/json:
                type: commonError
                example: !include /libraries/common/examples/500Response-example.json